[project]
name = "apr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyelftools>=0.32",
    "rich>=14.2.0",
    "typer>=0.20.0",
]
